### ISSUE TITLE
xml vs xml-rs?

### ISSUE THREAD

**Issue by bnoctis** [kornelski/xml-rs#14]
They both have homepage at https://lib.rs/crates/xml-rs, documentation at https://docs.rs/xml-rs, repository at [here]. But their readmes differ:

- xml says "add it with `cargo add xml-rs`"
- xml-rs says "add it with `cargo add xml`"

**Comment by kornelski** [comment]
You can use either one. The `xml` crate contains the latest stable version of this project. I'm planning to move everyone over to the `xml` crate once the project reaches 1.0.0.

But in the near future I'm sticking with xml-rs at 0.8 to keep existing users up to date.
