### ISSUE TITLE
Add default "xmlns" on ParserConfig2

### ISSUE THREAD

**Issue by hydroper** [kornelski/xml-rs#19]
Could you add this easy feature?

> Use a default namespace before parsing a XML document; i.e., xmlns="jetxml" by default at the root element, so that meta-attribute doesn't need to be specified.

**Comment by kornelski** [comment]
I assume you're dealing with broken XML that fails to specify the namespace it was supposed to have? 

This easy to implement, but I'm not sure that XML parsers should be implementing workarounds like that.

**Comment by hydroper** [comment]
I was going to use that to parse components for my ActionScript dialect, but I see. I might have to do some changes to my specification overview then.

**Comment by jlinnosa** [comment]
This would be convenient when handling "broken" fragments of a document. E.g. I came across this issue when trying to parse and manipulate Confluence page format with xml-rs... So far I've just used a modified version of this library that does what I need. 🤷‍♂️

**Comment by kornelski** [comment]
You can use `std::io::Chain` to wrap document fragment into an element that defines the namespaces.
