### ISSUE TITLE
Remove `RUSTSEC-2022-0048` from the RustSec Advisory Database

### ISSUE THREAD

**Issue by j3rrywan9** [kornelski/xml-rs#2]
Please remove `RUSTSEC-2022-0048` from the RustSec Advisory Database: https://github.com/rustsec/advisory-db/blob/main/crates/xml-rs/RUSTSEC-2022-0048.md, as it reads the crate is unmaintained.

**Comment by kornelski** [comment]
https://github.com/rustsec/advisory-db/pull/1691
