### ISSUE TITLE
Issues adding name and attribute value locations

### ISSUE THREAD

**Issue by hydroper** [kornelski/xml-rs#21]
There is a possible use case of using the `xml` crate for parsing user interface components written in MXML as part of the Apache Royale framework, where it's necessary to know the first and last line numbers and columns of a certain element name, attribute name, or attribute value (`(OwnedName, TextSpan)` or `(String, TextSpan)` for attribute values).

I've tried [forking this crate](https://github.com/hydroper/rust-xml), but it looks like the constructed spans have the same first `TextPosition` as the last `TextPosition`, pointing always to after the last character of the qualified name or attribute value. Here's an example of what I modified from xml-rs:

```rust
impl PullParser {
    fn read_qualified_name<F>(&mut self, t: Token, target: QualifiedNameTarget, on_name: F) -> Option<Result>
      where F: Fn(&mut PullParser, Token, (OwnedName, TextSpan)) -> Option<Result> {
        let start = self.lexer.position();

        ...

        let invoke_callback = move |this: &mut PullParser, t| {
            let name = this.take_buf();
            match name.parse() {
                Ok(name) => on_name(this, t, (name, TextSpan { start, end: this.lexer.position() })),
                Err(()) => Some(this.error(SyntaxError::InvalidQualifiedName(name.into()))),
            }
        };

        ...
    }
}
```

Here's a dummy debugging function:

```rust
#[test]
fn f1() {
    use crate::reader::XmlEvent;
    let my_xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<s:Application
    xmlns:fx="http://ns.adobe.com/flex"
    xmlns:s="library://ns.adobe.com/flex/spark"
    creationComplete="initialize()">
</s:Application>
    "#;
    let mut reader = EventReader::new(my_xml.as_bytes());
    while let Ok(event) = reader.next() {
        match event {
            XmlEvent::StartElement { name, attributes, .. } => {
                println!("{}", name.1);
                for attr in attributes {
                    println!("{}={}", attr.name.1, attr.value.1);
                }
            },
            XmlEvent::EndDocument => {
                break;
            },
            _ => {},
        }
    }
}
```

**Comment by kornelski** [comment]
This crate tracks positions only for reporting errors, so often the position is not updated until an error happens, and then only points to the invalid markup. 

Positions of elements in the source are not part of XML's data model. This crate won't be able to provide that.

**Comment by sify21** [comment]
@hydroper  I suppose this crate is what you need https://github.com/RazrFalcon/roxmltree

**Comment by hydroper** [comment]
@sify21 It looks to only store the location for the entire element rather than also the opening and closing tag names, the attribute names, the attribute values, and so on, but thanks for the pointer!
