### ISSUE TITLE
How to retrieve the `DOCTYPE` tag when parsing 

### ISSUE THREAD

**Issue by EstebanBorai** [kornelski/xml-rs#23]
I have been using this crate to parse SVGs, and I would like to rewrite them.

In order to parse these SVG files Im using the following `ParserConfig`:

```rust
        let parser = ParserConfig::new()
            .ignore_comments(false)
            .ignore_end_of_stream(false)
            .ignore_root_level_whitespace(false)
            .ignore_invalid_encoding_declarations(false)
            .create_reader(BufReader::new(r));
```

When looping through events produced by the parser, the `DOCTYPE` element is not being emitted.
I think this is a similar behavior as from this repo's local samples.

I can see the following XML:

https://github.com/kornelski/xml-rs/blob/8e772929162eb8a2bc86261bcb3b60d4eee593e9/tests/documents/sample_4.xml#L2

Where Doctype is included but in the events output, this one is missing:

https://github.com/kornelski/xml-rs/blob/main/tests/documents/sample_4_full.txt

I wonder if it would be possible to introduce support for it?

Thanks in advance!

**Comment by kornelski** [comment]
Unfortunately the parser does not keep information about the doctype when parsing

**Comment by EstebanBorai** [comment]
> Unfortunately the parser does not keep information about the doctype when parsing

Hi @kornelski, thanks so much for the quick reply!

Im willing to open a PR if you are okay supporting this as a feature!

Let me know your thoughts!

**Comment by kornelski** [comment]
Yes, PR is welcome.

You'll need to collect all the tokens in `inside_doctype()` into a new field in `self.data`, and then expose that as a getter on the reader, since changing events is not backwards-compatible.

Currently the library parses entities inside the doctype, but I assume that most users just need to preserve the whole doctype, so collecting the doctype as a `String` should be fine.

**Comment by EstebanBorai** [comment]
Great @kornelski! Feel free to assign me, I can work on this on the next days as I find time.

**Comment by EstebanBorai** [comment]
Hi @kornelski! Hope I find you well!

I have some progress on Doctype retrieval here:

https://github.com/kornelski/xml-rs/compare/main...EstebanBorai:xml-rs:main

A getter on `PullParser` is provided, so we can attempt to grab doctype from `MarkupData`.

Then I exposed the same getter in `EventReader` but given that this is not exposed an an event, I was wondering how could we use the `EventReader` to extract this data in the right moment?

I was thinking about checking for doctype on every event iteration, hoping that it has been filled with the actual value.

But Im afraid its not very optimum, what do you think? Thanks in advance!

**Comment by kornelski** [comment]
When you get the document start event, it's guaranteed to have seen the doctype already.

The code has the right approach. Use as_deref() to expose string in a more appropriate type. 

You can use write! macro instead of to_string() which avoids extra allocation.

**Comment by EstebanBorai** [comment]
> When you get the document start event, it's guaranteed to have seen the doctype already.
> 

Hi @kornelski, for this approach I would have to use the `PullParser` and perform the `doctype` call in the `XmlEvent::DocumentStart`, right?

Also, at some point do you plan to extend these events? So `doctype()` is not needed and instead a `XmlEvent` is used? This would allow to rewrite from `XmlEvent`s guaranteeing that order will match original.

**Comment by kornelski** [comment]
Done in b85c9b0

**Comment by kornelski** [comment]
It turns out it can't be in document start, because there can be PIs before the doctype, and waiting for a doctype would change order of events. 

I'm not adding a Doctype event yet, because that's a breaking change.

**Comment by EstebanBorai** [comment]
Hi @kornelski!

Gotcha! Thanks for jumping in!

Do you plan to publish an update any time soon?
