### ISSUE TITLE
Incorrect MSRV

### ISSUE THREAD

**Issue by FabianLars** [kornelski/xml-rs#24]
Hi, the newly released version 0.8.21 seems to require 1.61(?) not 1.59: https://github.com/tauri-apps/tauri/actions/runs/10251569176/job/28359905405 - not much of a problem for us as we'll downgrade it like the other crates but just wanted to give you a headsup :)

**Comment by kornelski** [comment]
Thanks. I'll probably leave it as is, since even the newer Rust version is super [old enough that CI tests are probably the only "users" of it](https://lib.rs/stats#rustc-usage) :)

**Comment by FabianLars** [comment]
Well, i agree that making your repo work with 1.59 isn't worth it (and it wouldn't make a difference for us) but wouldn't it be sensible to make the `msrv` config reflect reality?

**Comment by kornelski** [comment]
In the next release
