### ISSUE TITLE
Attribute `xmlns` is not coming

### ISSUE THREAD

**Issue by EstebanBorai** [kornelski/xml-rs#30]
Hi @kornelski!

I have been using this crate with the PullParser to retrieve SVG tags, one of my goals is to be able to rewrite the SVG as it comes originally.

Currently Im facing a particular behavior when trying to pull all attributes from the `SVG` tag, it seems like the attribute `xmlns` is not being retrieved as part of the `XmlElement`'s `attributes` collection.

Perhaps the Pull Parser should use a specific option so all attributes are retrieved?

Thanks in advance!

**Comment by kornelski** [comment]
XML has this weird thing that `xmlns` attributes are not real attributes. They're directives that control namespace mapping. The idea is that namespace prefixes are meaningless, all elements and attributes live in their absolute-URL namespaces, and you're just not supposed to care to preserve them. Make new ones when you rewrite the document :/

**Comment by EstebanBorai** [comment]
Thank you so much @kornelski!
