### ISSUE TITLE
Support for unicode control characters

### ISSUE THREAD

**Issue by tl-rodrigo-gryzinski** [kornelski/xml-rs#8]
According [to this wiki article](https://en.wikipedia.org/wiki/Valid_characters_in_XML), XML 1.0 should accept unicode characters in the ranges `U+007F–U+0084` and `U+0086–U+009F`, even though it notes their usage is highly discouraged.

Example:
```rs
const RAW: &str = "<?xml version=\"1.0\"?><Element>\u{007}</Element>";

fn main() {
    let parser = xml::EventReader::new(RAW.as_bytes());
    for res in parser {
        res.unwrap();
    }
}
```

```terminal
$ cargo run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 1:31, kind: Syntax("Invalid character U+0007") }', src/main.rs:7:13
```

**Comment by kornelski** [comment]
Eh, I thought I'd get away with following only the latest XML recommendation. But I guess I have to observe the version in the prolog, and adjust rules accordingly :/

**Comment by kornelski** [comment]
I'm testing against W3C's XML test suite, which has tests for illegal characters, and it's a whack-a-mole — some tests require it to be one way, other tests require it to be seemingly opposite. The combination of allowed ranges I've picked currently pass highest number of tests out of the options I've tried…

What's unclear to me is relationship between XML version in the document prolog, version of the XML spec, and allowed characters. Did the XML 1.1 spec obsolete 1.0 spec, so I can say the parser is 1.1 and parse everything by 1.1 rules? Or does `<?xml version="1.0"?>` mean I have to apply old spec's character restrictions to that particular document.

**Comment by kornelski** [comment]
You include `\07` in your example, but XML 1.0 fifth edition states:

https://www.w3.org/TR/xml/#charsets

> Char       ::=      #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]  /* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

**Comment by tl-rodrigo-gryzinski** [comment]
> What's unclear to me is relationship between XML version in the document prolog, version of the XML spec (including 1.0 1-4ed vs 1.0 5th ed), and allowed characters. Did the XML 1.1 spec obsolete 1.0 spec, so I can say the parser is 1.1 and parse everything by 1.1 rules? Or does <?xml version="1.0"?> mean I have to apply old spec's character restrictions to that particular document.

I see, didn't realize it'd be that complicated.

> Char ::= #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF] /* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

🤔 guess I am actually getting invalid XML from some producer with more relaxed XML serialization then, thanks 🙇.

**Comment by kornelski** [comment]
In 0.8.12 I've added XML-version-dependent check for allowed chars.
