### ISSUE TITLE
republish 0.2.2 version

### ISSUE THREAD

**Issue by patrickelectric** [kornelski/xml-rs#9]
Hi, it appears that 0.2.2 was removed from crates, can you reupload it ?
It's under: 9376d897a58fe4fbf27db7eb56a12463fd60bb89
My best regards.

**Comment by kornelski** [comment]
I've unyanked it, but I *strongly* suggest updating to the current version. It has important conformance and reliability improvements. The API is the same, so it should be an easy upgrade.

**Comment by patrickelectric** [comment]
Yes, it's updated, but there are some people that depend of projects that depend of such version still.
